---
title: "Brownlows Bets"
author: "Your Name"
date: "Year 2020"
output: 
  html_document:
    number_sections: true
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(tidyverse)
require(knitr)
```


<!-- We recommend you use git branches -- create a separate branch for each major section i.e. Introduction, Methods, Results, Inferential Results, and Discussion and Conclusions - leave the YAML block untouched until the final merge where you put in your own name !-->

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->

 At the first day of class there are 35 students in Math Statistics class and professor Brownlow always proposes this bet to his students "I will wager $2 to your bet of $1 that at least two people in today's class have  the same birthday.  He tells me he has made that bet 637 times so far. Where do you think his profits are? Discuss this in a markdown document
 
Report git commit structure:
There are 3 questions and there should be at least 3 separate commits, at least one dealing with each of the 3 questions.
1. What are the fair odds for a bet on matching birthdays in a 35 person class.
2. For what size class is a 2:1 odds bet fair.
3. How much money would Brownlow be expected to end up with if the bets went as described.

# What are the fair odds  


<!--Decide on your methods:  In this section explain the approach you will take to attack the issue --- how will you decide on a likely estimate of professor Brownlow's earnings or losses after 637 bets. Also explain how you construct a 95% confidence interval about your estimate of his winnings !-->


# What size of class makes the 2:1 bet fair?  
<!--Explain and display the results of your method of coming up with the estimate of professor Brownlows betting profits!-->


# In the class and payoff as described what is a 95% confidence interval for Brownlow's earnings?
  
<!--Explain and display your method of coming up with a 95% confidence interval of  professor Brownlows winnings (or losings)-->


# Discussion and Conclusion

<!--Discussion and conclusion here.  If professor Brownlow is consistantly making or losing money how could he change his payout so that his profits center on zero?  Also discuss what size his class should be in order to have his current scheme balance at zero profit.!-->

